version: '3.2'
services:
  nc_scraper_bitstamp:
    build: docker/nodejs
    image: dtonder/nc_nodejs
    restart: on-failure
    links:
      - nc_rabbitmq
    volumes:
      - /srv/neuralcoin_deploy/current:/code
    deploy:
      placement:
        constraints:
          - node.role == manager
    command: wait-for-it nc_rabbitmq:5672 -- node /code/nodejs/bitstamp-feed.js

  nc_scraper_bitfinex:
    build: docker/nodejs
    image: dtonder/nc_nodejs
    restart: on-failure
    links:
      - nc_rabbitmq
    volumes:
      - /srv/neuralcoin_deploy/current:/code
    deploy:
      placement:
        constraints:
          - node.role == manager
    command: wait-for-it nc_rabbitmq:5672 -- node /code/nodejs/bitfinex-feed.js

  nc_scraper_poloniex:
    build: docker/nodejs
    image: dtonder/nc_nodejs
    restart: on-failure
    links:
      - nc_rabbitmq
    volumes:
      - /srv/neuralcoin_deploy/current:/code
    deploy:
      placement:
        constraints:
          - node.role == manager
    command: wait-for-it nc_rabbitmq:5672 -- node /code/nodejs/poloniex-feed.js

  nc_scraper_bittrex:
    build: docker/nodejs
    image: dtonder/nc_nodejs
    restart: on-failure
    links:
      - nc_rabbitmq
    volumes:
      - /srv/neuralcoin_deploy/current:/code
    deploy:
      placement:
        constraints:
          - node.role == manager
    command: wait-for-it nc_rabbitmq:5672 -- node /code/nodejs/bittrex-feed.js

  nc_scraper_bittrex_order_book:
    build: docker/nodejs
    image: dtonder/nc_nodejs
    restart: unless-stopped
    links:
      - nc_rabbitmq
    volumes:
      - ./:/code
    command: wait-for-it nc_rabbitmq:5672 -- node /code/nodejs/bittrex-orderbook.js

  nc_trades_broker:
    build: docker/php
    image: dtonder/nc_php
    user: www-data
    links:
      - nc_rabbitmq
      - nc_websocket_server
    volumes:
      - /srv/neuralcoin_deploy/current:/code
      - /srv/neuralcoin_deploy/current/var/log:/code/var/logs
    deploy:
      placement:
        constraints:
          - node.role == manager
    restart: on-failure
    command: wait-for-it nc_rabbitmq:5672 -- wait-for-it -t 30 nc_websocket_server:8081 -- bin/env-console rabbitmq:consumer trades_listener -vvv

  nc_order_book_consumer:
    build: docker/php
    image: dtonder/nc_php
    user: www-data
    links:
      - nc_rabbitmq
      - nc_db
    volumes:
      - ./:/code
      - ./var/log:/code/var/logs
    restart: unless-stopped
    command: wait-for-it nc_rabbitmq:5672 -- wait-for-it nc_db:3306 -- bin/env-console rabbitmq:consumer order_book_listener -vvv

  nc_training_status_listener:
    build: docker/php
    image: dtonder/nc_php
    user: www-data
    links:
      - nc_rabbitmq
      - nc_websocket_server
    volumes:
      - /srv/neuralcoin_deploy/current:/code
      - /srv/neuralcoin_deploy/current/var/networks:/code/var/network-data
      - /srv/neuralcoin_deploy/current/var/log:/code/var/logs
      - /srv/neuralcoin_deploy/current/var/shared-images:/code/web/images
    deploy:
      placement:
        constraints:
          - node.role == manager
    restart: on-failure
    command: wait-for-it nc_rabbitmq:5672 -- bin/env-console rabbitmq:consumer training_listener -vvv

  nc_training_data_assembler:
    build: docker/php
    image: dtonder/nc_php
    user: www-data
    links:
      - nc_rabbitmq
      - nc_websocket_server
    volumes:
       - /srv/neuralcoin_deploy/current:/code
       - /srv/neuralcoin_deploy/current/var/networks:/code/var/network-data
       - /srv/neuralcoin_deploy/current/var/log:/code/var/logs
    restart: on-failure
    deploy:
      placement:
        constraints:
          - node.role == manager
    command: wait-for-it nc_rabbitmq:5672 -- bin/env-console rabbitmq:consumer assemble_training_data -vvv

  nc_prediction_processor:
    build: docker/php
    image: dtonder/nc_php
    user: www-data
    links:
      - nc_rabbitmq
      - nc_websocket_server
    volumes:
      - /srv/neuralcoin_deploy/current:/code
      - /srv/neuralcoin_deploy/current/var/networks:/code/var/network-data
      - /srv/neuralcoin_deploy/current/var/log:/code/var/logs
    deploy:
      placement:
        constraints:
          - node.role == manager
    restart: on-failure
    command: wait-for-it nc_rabbitmq:5672 -- bin/env-console rabbitmq:consumer request_prediction -vvv

  nc_phpfpm:
    build: docker/php
    image: dtonder/nc_php
    user: www-data
    links:
      - nc_rabbitmq
      - nc_redis
    volumes:
      - composer_cache:/var/www/.composer
      - /srv/neuralcoin_deploy/current:/code
      - /srv/neuralcoin_deploy/current/var/networks:/code/var/network-data
      - /srv/neuralcoin_deploy/current/var/log:/code/var/logs
      - /srv/neuralcoin_deploy/current/var/shared-images:/code/web/images
    deploy:
      placement:
        constraints:
          - node.role == manager
    command: wait-for-it nc_rabbitmq:5672 -- php-fpm

  nc_websocket_server:
    build: docker/php
    image: dtonder/nc_php
    user: www-data
    links:
      - nc_rabbitmq
      - nc_redis
    ports:
      - '8081:8081'
    volumes:
      - /srv/neuralcoin_deploy/current:/code
      - /srv/neuralcoin_deploy/current/var/networks:/code/var/network-data
      - /srv/neuralcoin_deploy/current/var/log:/code/var/logs
    deploy:
      placement:
        constraints:
          - node.role == manager
    restart: on-failure
    command: wait-for-it nc_rabbitmq:5672 -- bin/env-console neuralcoin:websocket:server -vvv

  nc_nginx:
    build: docker/nginx
    image: dtonder/nc_nginx
    volumes:
      - /srv/neuralcoin_deploy/current:/code
      - /srv/neuralcoin_deploy/current/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=neuralcoin.local
    links:
      - nc_phpfpm
      - nc_websocket_server
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - '80:80'
    command: wait-for-it nc_phpfpm:9000 -- wait-for-it nc_websocket_server:8081 -- nginx

  #management is on port 15672
  nc_rabbitmq:
    image: rabbitmq:management
    deploy:
      placement:
        constraints:
          - node.role == manager

  nc_redis:
    image: redis:3.2
    deploy:
      placement:
        constraints:
          - node.role == manager

  nc_network_creator:
    build: docker/python
    image: dtonder/nc_python
    user: www-data
    links:
      - nc_rabbitmq
    volumes:
      - /srv/neuralcoin_deploy/current:/code
      - /srv/neuralcoin_deploy/current/var/networks:/code/var/network-data
    restart: on-failure
    command: wait-for-it nc_rabbitmq:5672 -- python -u python/consume-create-network.py

  nc_network_trainer:
    build: docker/python
    image: dtonder/nc_python
    user: www-data
    links:
      - nc_rabbitmq
    volumes:
      - /srv/neuralcoin_deploy/current:/code
      - /srv/neuralcoin_deploy/current/var/networks:/code/var/network-data
    deploy:
      placement:
        constraints:
          - node.role != manager
    restart: on-failure
    command: wait-for-it nc_rabbitmq:5672 -- python -u python/consume-train-network.py

  nc_get_prediction:
    build: docker/python
    image: dtonder/nc_python
    user: www-data
    restart: on-failure
    links:
      - nc_rabbitmq
    volumes:
      - /srv/neuralcoin_deploy/current:/code
      - /srv/neuralcoin_deploy/current/var/networks:/code/var/network-data
    command: wait-for-it nc_rabbitmq:5672 -- python -u python/consume-get-prediction.py

  nc_cron:
    build: docker/php
    image: dtonder/nc_python
    user: root
    restart: on-failure
    links:
      - nc_rabbitmq
      - nc_redis
    volumes:
      - /srv/neuralcoin_deploy/current:/code
      - /srv/neuralcoin_deploy/current/var/networks:/code/var/network-data
      - /srv/neuralcoin_deploy/current/var/log:/code/var/logs
      - /srv/neuralcoin_deploy/current/docker/crontab:/etc/crontab
    command: wait-for-it nc_rabbitmq:5672 -- bin/run-crons

volumes:
  mysql_data:
  composer_cache:
  network_storage:

